//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanBanPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen_QuanTri
    {
        public int MaAD { get; set; }
        public string MaQuyen { get; set; }
        public string GhiChu { get; set; }
    
        public virtual PhanQuyen PhanQuyen { get; set; }
        public virtual QuanTri QuanTri { get; set; }
    }
}
